version: "3.12"

services:
  app:
    container_name: app
    build: 
      context: ./app
      dockerfile: DockerFile
    ports:
      - "5050:5050"
    environment:
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres
      - JWT_SECRET_KEY=321dg4nt4h5432!
    depends_on:
      - flask_db
  flask_db:
    container_name: flask_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
    