apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "flask"
  namespace: "default"
  labels:
    app: "flask"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "flask"
  template:
    metadata:
      labels:
        app: "flask"
    spec:
      containers:
      - name: "flask"
        image: "flask-app"
        imagePullPolicy: Never
        ports:
          - containerPort: 5000
        env: 
          - name: DB_URL
            valueFrom:
              secretKeyRef:
                key: "POSTGRES_URI"
                name: "secret"
          - name: JWT_SECRET_KEY
            valueFrom:
              secretKeyRef:
                key: "JWT_SECRET_KEY"
                name: "secret"
          - name: MODEL_URI
            value: "http://huggingface_container:8000"

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    service: flask
spec:
  selector:
    app: flask
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    